# Generated by Django 3.1.1 on 2021-03-31 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=20)),
                ('Messages', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
